### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by cstroe** [alistairrutherford/libgdx-demos#4]
It seems the dependencies of this project are not available anymore and therefore it cannot be compiled.

**Comment by alistairrutherford** [comment]
I'll take a look.

**Comment by alistairrutherford** [comment]
Yeah there is something going on with the libgdx repo. You could try updating the libgdx ref to the latest version. In the meantime I am converting it to use gradle and Android Studio.

**Comment by BackPackerDz** [comment]
Same issue :(

**Comment by alistairrutherford** [comment]
Yeah I am still working on this. I'm getting there slowly.

**Comment by alistairrutherford** [comment]
Okay I have updated the projects to use Android Studio and gradle. Build instructions here:

https://github.com/alistairrutherford/libgdx-demos/wiki/Build-Instructions

**Comment by alistairrutherford** [comment]
Right. I am closing this as I think I have fixed it. Thanks to all for the feedback.
